"""Type stubs for the native Rust extension module."""

class IdGenerator:
    def __new__(cls) -> IdGenerator: ...
    def __call__(self) -> str: ...
    def generate_at(self, timestamp_ms: int) -> str: ...
    def reset(self) -> None: ...

def generate_id() -> str: ...
def generate_id_at(timestamp_ms: int) -> str: ...
def extract_timestamp_ms(id: str) -> int: ...
def to_bytes(id: str) -> bytes: ...
def from_bytes(data: bytes) -> str: ...
def reset_thread_local() -> None: ...
