"""Type stubs for the native Rust extension module."""

class IdGenerator:
    def __new__(cls) -> IdGenerator: ...
    def generate(self) -> str: ...
    def generate_at(self, timestamp_ms: int) -> str: ...
    def reset(self) -> None: ...

def generate_id() -> str: ...
def generate_id_at(timestamp_ms: int) -> str: ...
def extract_timestamp_ms(id: str) -> int: ...
def to_bytes(id: str) -> bytes: ...
def from_bytes(data: bytes) -> str: ...
def reset_thread_local() -> None: ...

ALPHABET: str
BASE: int
MAX_TIMESTAMP: int
ID_LENGTH: int
TIMESTAMP_CHAR_COUNT: int
COUNTER_CHAR_COUNT: int
RANDOM_CHAR_COUNT: int
